# Generated by Django 5.1.1 on 2024-10-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Espaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="data_horario",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="espaco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="agendamento.espaco"
            ),
        ),
    ]
